import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/lib/AuthProvider';
import { NavBar } from '@/components/NavBar';

export const metadata: Metadata = {
  title: 'Yooni Page',
  description: 'Generated by Yooni'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <AuthProvider>
          <NavBar />
          <div className="p-8">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
