import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/lib/AuthProvider';

export const metadata: Metadata = {
  title: 'Yooni Page',
  description: 'Generated by Yooni'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
